<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-CNG635MQ" failures="1" tests="6" name="Surefire test" time="66.161" errors="0" timestamp="2024-05-13T09:33:25 IST">
  <testcase classname="pageFactor.BaseTest" name="testFail" time="0.008"/>
  <testcase classname="pageFactor.BaseTest" name="testFail" time="0.0"/>
  <testcase classname="pageFactor.PageFactoringTest" name="ecommerceTest" time="15.165"/>
  <testcase classname="pageFactor.PageFactoringTest" name="ecommerceTest" time="11.355"/>
  <testcase classname="pageFactor.StandAloneTest" name="runTest" time="14.021"/>
  <testcase classname="pageFactor.StandAloneTest" name="runTest" time="9.356">
    <failure type="java.lang.AssertionError" message="expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [2]
at pageFactor.StandAloneTest.runTest(StandAloneTest.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- runTest -->
</testsuite> <!-- Surefire test -->
